/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunnykulshrestha
 */
public class Issue_details extends javax.swing.JFrame {

    /**
     * Creates new form Issue_details
     */
           
    /**
     *
     */

    /**
     *
     */
    public Issue_details() {
        initComponents();
        getData();
    }
DefaultTableModel modle;
    public void clearTable(){
        DefaultTableModel model=(DefaultTableModel)book_table.getModel();
           model.setRowCount(0);
    }
     public void getData(){
         
            Connection con=(Connection) DBConnection.getConnection();
                    try {
                        String sql="select *from issue_book ";
            PreparedStatement pst=con.prepareStatement(sql);
//            pst.setString(1,date_issue.getFormatoFecha());
//            pst.setString(2,due_date.getFormatoFecha());
                     
             ResultSet rs=pst.executeQuery();
        while(rs.next())
       {  String id=rs.getString("id");
           String book_id=rs.getString("book_id");
           String book_name=rs.getString("book_name");
           String student_id=rs.getString("student_id");
           String student_name=rs.getString("student_name");
           String issue_date=rs.getString("issue_date");
           String due_date=rs.getString("return_date");
           String status=rs.getString("status");
           Object obj[]={id,book_id,book_name,student_id,student_name,issue_date,due_date,status};
           modle=(DefaultTableModel) book_table.getModel();
           modle.addRow(obj);
           
       }
        } catch (SQLException ex) {
            Logger.getLogger(Issue_details.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     void search(){
         Date d1=date_issue.getDatoFecha();
        Date d2=due_date.getDatoFecha();
        long l1=d1.getTime();
        long l2=d2.getTime();
       java.sql.Date from=new  java.sql.Date(l1);
       java.sql.Date to=new  java.sql.Date(l2);
       Connection con=(Connection) DBConnection.getConnection();
                    try {
                        String sql="select *from issue_book where issue_date between ? and ? ";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setDate(1, from);
            pst.setDate(2, to);
            
            ResultSet  rs=pst.executeQuery();  
             while(rs.next())
       {  String id=rs.getString("id");
           String book_id=rs.getString("book_id");
           String book_name=rs.getString("book_name");
           String student_id=rs.getString("student_id");
           String student_name=rs.getString("student_name");
           String issue_date=rs.getString("issue_date");
           String due_date=rs.getString("return_date");
           String status=rs.getString("status");
           Object obj[]={id,book_id,book_name,student_id,student_name,issue_date,due_date,status};
           modle=(DefaultTableModel) book_table.getModel();
           modle.addRow(obj);
           
       }

            
                    }
                    catch (SQLException ex) {
            Logger.getLogger(Issue_details.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        book_table = new rojeru_san.complementos.RSTableMetro();
        jPanel5 = new javax.swing.JPanel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jLabel6 = new javax.swing.JLabel();
        date_issue = new rojeru_san.componentes.RSDateChooser();
        jLabel7 = new javax.swing.JLabel();
        due_date = new rojeru_san.componentes.RSDateChooser();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-09-19 at 2.15.02 PM.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 190));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Id", "Book Name", "Student Id", "Student Name", "Issue Date", "Return Date", "Status"
            }
        ));
        book_table.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        book_table.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        book_table.setColorFilasForeground1(new java.awt.Color(102, 0, 204));
        book_table.setColorFilasForeground2(new java.awt.Color(102, 0, 204));
        book_table.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        book_table.setFuenteFilas(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        book_table.setFuenteFilasSelect(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        book_table.setRowHeight(40);
        book_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                book_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(book_table);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 1150, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(204, 0, 51));
        rSMaterialButtonCircle1.setText("Search");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel5.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 200, 40));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Issue From :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        date_issue.setBackground(new java.awt.Color(204, 0, 51));
        date_issue.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        date_issue.setForeground(new java.awt.Color(204, 0, 51));
        date_issue.setToolTipText("");
        date_issue.setColorBackground(new java.awt.Color(204, 0, 51));
        date_issue.setColorForeground(new java.awt.Color(204, 0, 51));
        date_issue.setFuente(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        date_issue.setPlaceholder("Select Issue Date");
        date_issue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_issueFocusLost(evt);
            }
        });
        jPanel5.add(date_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 310, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Issue Till :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        due_date.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        due_date.setForeground(new java.awt.Color(204, 0, 51));
        due_date.setToolTipText("");
        due_date.setColorBackground(new java.awt.Color(204, 0, 51));
        due_date.setColorForeground(new java.awt.Color(204, 0, 51));
        due_date.setFuente(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        due_date.setPlaceholder("Select Issue Date");
        due_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                due_dateFocusLost(evt);
            }
        });
        jPanel5.add(due_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 310, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 170));

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-09-19 at 2.20.49 PM.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -500, 960, 1170));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1430, 670));

        setSize(new java.awt.Dimension(1433, 888));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void date_issueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_issueFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_date_issueFocusLost

    private void due_dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_due_dateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_due_dateFocusLost

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        clearTable();
        search();
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void book_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_tableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_book_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro book_table;
    private rojeru_san.componentes.RSDateChooser date_issue;
    private rojeru_san.componentes.RSDateChooser due_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    // End of variables declaration//GEN-END:variables
}
