/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;


import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sunnykulshrestha
 */
public class Issue_Book extends javax.swing.JFrame {

    /**
     * Creates new form Issue_Book
     */
    public Issue_Book() {
        initComponents();
    }
int student_id,book_id;
long diff;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean Bookdata(){
       
         book_id=Integer.parseInt(txt_Bookid.getText());
       try {
           
             Connection con=DBConnection.getConnection();
              PreparedStatement  pst=con.prepareStatement("Select *from book where book_id=?");
                  pst.setInt(1,book_id);
           
            
           
           ResultSet rs=pst.executeQuery();
           
            if(rs.next())
            {    book_invaild.setText("");

                Book_id.setText((String.valueOf(rs.getInt("book_id"))));
                Book_name.setText(rs.getString("book_name"));
                Author.setText(rs.getString("book_author"));
                Quantity.setText((String.valueOf(rs.getInt("Quantity"))));
                return true;
            }
            else
            {   Book_id.setText("");
                Book_name.setText("");
                Author.setText("");
                Quantity.setText("");
                book_invaild.setText("Invaild Book Id");
            }
            
            
             

        } catch (SQLException ex) {
            Logger.getLogger(Issue_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
return false;
    }
    public boolean studentdata(){
       
         student_id=Integer.parseInt(txt_studentid.getText());
       try {
           
             Connection con=DBConnection.getConnection();
              PreparedStatement  pst=con.prepareStatement("Select *from student where student_id=?");
                  pst.setInt(1,student_id);
           
            
           
           ResultSet rs=pst.executeQuery();
           
            if(rs.next())
            {   student_invaild.setText("");
                Student_id.setText((String.valueOf(rs.getInt("student_id"))));
                Student_name.setText(rs.getString("student_name"));
                phone.setText(rs.getString("contact"));
                branch.setText(rs.getString("branch"));
                return true;
            }
            else
            {   Student_id.setText("");
                Student_name.setText("");
                phone.setText("");
                branch.setText("");
                student_invaild.setText("Invaild Book Id");
            }
            
             

        } catch (SQLException ex) {
            Logger.getLogger(Issue_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
return false;
    }
    
    public boolean book_issue(){
        String student_name=Student_name.getText();
        String book_name=Book_name.getText();
        Date issue_date=date_issue.getDatoFecha();
        Date due_date=Date_due.getDatoFecha();
        long l1,l2;
        l1=issue_date.getTime();
        l2=due_date.getTime();
         diff=l2-l1;
        diff=(diff / (1000 * 60 * 60 * 24)) ;
       
        
        java.sql.Date issue_d=new java.sql.Date(l1);
        java.sql.Date due_d=new java.sql.Date(l2);
        Connection con=DBConnection.getConnection();
        try {
            PreparedStatement  pst=con.prepareStatement("insert into issue_book(book_id,book_name,student_id,student_name,issue_date,return_date,status) values(?,?,?,?,?,?,?)");
            pst.setInt(1,book_id);
            pst.setString(2,book_name);
            pst.setInt(3,student_id);
            pst.setString(4,student_name);
            pst.setDate(5,issue_d);
            pst.setDate(6,due_d);
            pst.setString(7,"Pending");
            int rs=pst.executeUpdate();
            if(rs>0) return true;
            
        } catch (SQLException ex) {
            Logger.getLogger(Issue_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
            return false;      
        
        
        
    }
    public void count(){
        Connection con =DBConnection.getConnection();
        try {
            PreparedStatement pst=con.prepareStatement("Update book set quantity=quantity-1 where book_id=?");
            pst.setInt(1,book_id);
            pst.executeUpdate();
            Bookdata();
        } catch (SQLException ex) {
            Logger.getLogger(Issue_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public boolean vaild(){
        Connection con =DBConnection.getConnection();
        try {
            String sql="select *from issue_book where student_id=? and book_id=? and status=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setInt(1,student_id);
            pst.setInt(2,book_id);
            pst.setString(3,"Pending");
            

            ResultSet rs=pst.executeQuery();
            
            
            if(rs.next()){ 
                
                return false;
            
            }
            }
        
       catch (SQLException ex) {
            Logger.getLogger(Issue_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
    public boolean bookCount(){
       if(Quantity.getText().equals("0")) return false;
        return true;
    }
    public boolean issueDate()
    {
        Date issue_date=date_issue.getDatoFecha();
        Date cur=new Date();
        long t1=issue_date.getTime();
        long t2=cur.getTime();
        long dif=t1-t2;
         dif=(dif / (1000 * 60 * 60 * 24)) ;
        
        if(dif<0)
        { 
        return false;}
        return true;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Book_id = new javax.swing.JLabel();
        Book_name = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        book_invaild = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        branch = new javax.swing.JLabel();
        Student_id = new javax.swing.JLabel();
        Student_name = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        student_invaild = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_Bookid = new app.bolivia.swing.JCTextField();
        txt_studentid = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        date_issue = new rojeru_san.componentes.RSDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Date_due = new rojeru_san.componentes.RSDateChooser();
        Add = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText("Book Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 105, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Id:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 334, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 411, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Author:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 488, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 565, -1, -1));

        Quantity.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 230, 30));

        Book_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Book_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 334, 230, 30));

        Book_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Book_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 230, 30));

        Author.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Author.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 230, 30));

        book_invaild.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        book_invaild.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(book_invaild, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 230, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 810));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student Id:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 334, -1, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student Name:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 411, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone no :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 488, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Branch :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 565, -1, -1));

        branch.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        branch.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 230, 30));

        Student_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Student_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(Student_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        Student_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Student_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(Student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 230, 30));

        phone.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 230, 30));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Student_Registration_100px_2.png"))); // NOI18N
        jLabel13.setText("Student Details");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        student_invaild.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        student_invaild.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(student_invaild, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 230, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 420, 810));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel8.setText("Issue Book");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 340, -1));

        jLabel15.setFont(new java.awt.Font("Kailasa", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 102));
        jLabel15.setText("Enter Book Id :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 130, -1));

        txt_Bookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        txt_Bookid.setForeground(new java.awt.Color(255, 102, 102));
        txt_Bookid.setPhColor(new java.awt.Color(255, 102, 102));
        txt_Bookid.setPlaceholder("Enter Book Id");
        txt_Bookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_BookidFocusLost(evt);
            }
        });
        txt_Bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BookidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 310, 30));

        txt_studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        txt_studentid.setForeground(new java.awt.Color(255, 102, 102));
        txt_studentid.setPhColor(new java.awt.Color(255, 102, 102));
        txt_studentid.setPlaceholder("Enter Book Id");
        txt_studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentidFocusLost(evt);
            }
        });
        txt_studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 310, 30));

        jLabel16.setFont(new java.awt.Font("Kailasa", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setText("Issue Date :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 110, -1));

        date_issue.setBackground(new java.awt.Color(255, 102, 102));
        date_issue.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        date_issue.setForeground(new java.awt.Color(255, 102, 102));
        date_issue.setToolTipText("");
        date_issue.setColorBackground(new java.awt.Color(255, 102, 102));
        date_issue.setColorForeground(new java.awt.Color(255, 102, 102));
        date_issue.setFuente(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        date_issue.setPlaceholder("Select Issue Date");
        date_issue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_issueFocusLost(evt);
            }
        });
        jPanel1.add(date_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 510, 310, -1));

        jLabel17.setFont(new java.awt.Font("Kailasa", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 102));
        jLabel17.setText("Enter Student Id :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 150, -1));

        jLabel18.setFont(new java.awt.Font("Kailasa", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 102));
        jLabel18.setText("Due Date :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 620, 110, -1));

        Date_due.setBackground(new java.awt.Color(255, 102, 102));
        Date_due.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        Date_due.setForeground(new java.awt.Color(255, 102, 102));
        Date_due.setColorBackground(new java.awt.Color(255, 102, 102));
        Date_due.setColorForeground(new java.awt.Color(255, 102, 102));
        Date_due.setFuente(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Date_due.setPlaceholder("Select Issue Date");
        Date_due.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Date_dueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Date_dueFocusLost(evt);
            }
        });
        jPanel1.add(Date_due, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 310, -1));

        Add.setBackground(new java.awt.Color(255, 102, 102));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 690, 380, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 800));

        setSize(new java.awt.Dimension(1411, 831));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home=new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        
        jPanel3.setBackground(Color.red);

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(102,0,204));

    }//GEN-LAST:event_jLabel1MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel3MouseEntered
    
    private void txt_BookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BookidFocusLost
          Bookdata();
          
    }//GEN-LAST:event_txt_BookidFocusLost

    private void txt_BookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BookidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_BookidActionPerformed

    private void txt_studentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentidFocusLost
        // TODO add your handling code here:
        studentdata();
          
       
    }//GEN-LAST:event_txt_studentidFocusLost

    private void txt_studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentidActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        Date issue_date=date_issue.getDatoFecha();
        Date due_date=Date_due.getDatoFecha();
        long l1,l2;
        l1=issue_date.getTime();
        l2=due_date.getTime();
         diff=l2-l1;
        diff=(diff / (1000 * 60 * 60 * 24)) ;
        if(issueDate()){
        if(diff>0){
        if(bookCount())
        {
            
        
        if(vaild())
        {
         if(book_issue())
        {
            JOptionPane.showMessageDialog(this,"Book Issued");
            count();
            Book_id.setText("");
                Book_name.setText("");
                Author.setText("");
                Quantity.setText("");
                Student_id.setText("");
                Student_name.setText("");
                phone.setText("");
                branch.setText("");
                txt_Bookid.setText("");
                txt_studentid.setText("");
                
        }
        else
            JOptionPane.showMessageDialog(this,"Book not Issued");
        }
        else
             JOptionPane.showMessageDialog(this,"Book Already Issued");
        }
        else
    JOptionPane.showMessageDialog(this,"Book is Not Present in Library");
        }
        
        else
            JOptionPane.showMessageDialog(this,"Enter the vaild date");
        }
        else
            JOptionPane.showMessageDialog(this,"Enter the vaild date");

    }//GEN-LAST:event_AddActionPerformed

    private void Date_dueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Date_dueFocusLost
        // TODO add your handling code here:
       
                    
    }//GEN-LAST:event_Date_dueFocusLost

    private void Date_dueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Date_dueFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Date_dueFocusGained

    private void date_issueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_issueFocusLost
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Book is Not Present in Library");
    }//GEN-LAST:event_date_issueFocusLost
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle Add;
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Book_id;
    private javax.swing.JLabel Book_name;
    private rojeru_san.componentes.RSDateChooser Date_due;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Student_id;
    private javax.swing.JLabel Student_name;
    private javax.swing.JLabel book_invaild;
    private javax.swing.JLabel branch;
    private rojeru_san.componentes.RSDateChooser date_issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel student_invaild;
    private app.bolivia.swing.JCTextField txt_Bookid;
    private app.bolivia.swing.JCTextField txt_studentid;
    // End of variables declaration//GEN-END:variables
}
