/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;


import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sunnykulshrestha
 */
public class return_Book extends javax.swing.JFrame {

    /**
     * Creates new form Issue_Book
     */
    public return_Book() {
        initComponents();
    }
int book_id,student_id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
public void count(){
        Connection con =DBConnection.getConnection();
        try {
            PreparedStatement pst=con.prepareStatement("Update book set quantity=quantity+1 where book_id=?");
            pst.setInt(1,book_id);
            pst.executeUpdate();
            PreparedStatement pst2=con.prepareStatement("Update issue_Book set status=? where book_id=? and student_id=?");
            pst2.setString(1,"Submit");
            pst2.setInt(2,book_id);
            pst2.setInt(3,student_id);
            int rs=pst2.executeUpdate();
            if(rs>0){ JOptionPane.showMessageDialog(this, "Book Return");
            txt_Bookid.setText("");
              txt_studentid.setText("");
              Penalty.setText("");
            }
            
            else JOptionPane.showMessageDialog(this,"Book Not Return");
                Issue_id.setText("");
              
              Book_name.setText("");
              Student_name.setText("");
              Issue_date.setText("");
              due_date.setText("");
              
        } catch (SQLException ex) {
            Logger.getLogger(return_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
   public boolean issue_id(){
       book_id=Integer.parseInt(txt_Bookid.getText());
        student_id=Integer.parseInt(txt_studentid.getText());
            Connection con=DBConnection.getConnection();
            String sql="Select *from issue_book where student_id=? and book_id=? and status=?";
                                     
        try {
            PreparedStatement pst=con.prepareStatement(sql);
            
            
            pst.setInt(1,student_id);
            pst.setInt(2,book_id);
          pst.setString(3,"Pending");
          ResultSet res=pst.executeQuery();
          
          if(res.next())
          { 
              Issue_id.setText(String.valueOf(res.getInt("id")));
              
              Book_name.setText(res.getString("book_name"));
              Student_name.setText(res.getString("student_name"));
              Issue_date.setText(res.getString("issue_date"));
              due_date.setText(res.getString("return_date"));
              String d1=due_date.getText();
              Date cur=new Date();
               SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");  
                try {  
                    Date d2=formatter1.parse(d1);
                    long da1=cur.getTime();
                    long da2=d2.getTime();
                    long diff=da2-da1;
                    diff=(diff/(1000*24*60*60));
                    if(diff<0)
                    {
                        Penalty.setText(String.valueOf(Math.abs(diff)*50));
                    }
                    else
                    {   
                        Penalty.setText("0");
                    }
                    
                } catch (ParseException ex) {
                    return false;

                }
              
               return true;
          }
          
        } catch (SQLException ex) {
            Logger.getLogger(return_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
   }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        due_date = new javax.swing.JLabel();
        Issue_id = new javax.swing.JLabel();
        Book_name = new javax.swing.JLabel();
        Student_name = new javax.swing.JLabel();
        Penalty = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Issue_date = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Penalty1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_Bookid = new app.bolivia.swing.JCTextField();
        txt_studentid = new app.bolivia.swing.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        Add = new rojerusan.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Add1 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText("Book Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 105, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Id:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        due.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        due.setForeground(new java.awt.Color(255, 255, 255));
        due.setText("Due Date :");
        jPanel2.add(due, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 120, 30));

        due_date.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        due_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(due_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 230, 30));

        Issue_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Issue_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Issue_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, 30));

        Book_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Book_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 405, 230, 30));

        Student_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Student_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 230, 30));

        Penalty.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Penalty.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Penalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, 230, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Issue Date :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        Issue_date.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Issue_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Issue_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 230, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Penalty :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 120, 30));

        Penalty1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Penalty1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Penalty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 230, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 420, 820));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel8.setText("Issue Book");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 340, -1));

        jLabel15.setFont(new java.awt.Font("Kailasa", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 102));
        jLabel15.setText("Enter Book Id :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 130, -1));

        txt_Bookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        txt_Bookid.setForeground(new java.awt.Color(255, 102, 102));
        txt_Bookid.setPhColor(new java.awt.Color(255, 102, 102));
        txt_Bookid.setPlaceholder("Enter Book Id");
        txt_Bookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_BookidFocusLost(evt);
            }
        });
        txt_Bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BookidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 300, 200, 30));

        txt_studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        txt_studentid.setForeground(new java.awt.Color(255, 102, 102));
        txt_studentid.setPhColor(new java.awt.Color(255, 102, 102));
        txt_studentid.setPlaceholder("Enter Student Id");
        txt_studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentidFocusLost(evt);
            }
        });
        txt_studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 410, -1, 30));

        jLabel17.setFont(new java.awt.Font("Kailasa", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 102));
        jLabel17.setText("Enter Student Id :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, 150, -1));

        Add.setBackground(new java.awt.Color(255, 102, 102));
        Add.setText("Return Book");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 620, 320, 100));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-09-19 at 12.38.55 AM.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 830));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 760));

        Add1.setBackground(new java.awt.Color(102, 0, 204));
        Add1.setText("Find Book");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        jPanel1.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 500, 320, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 800));

        setSize(new java.awt.Dimension(1411, 786));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home=new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        
       

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jLabel1MouseExited
    
    private void txt_BookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BookidFocusLost
          
          
    }//GEN-LAST:event_txt_BookidFocusLost

    private void txt_BookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BookidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_BookidActionPerformed

    private void txt_studentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentidFocusLost
        // TODO add your handling code here:
        
          
       
    }//GEN-LAST:event_txt_studentidFocusLost

    private void txt_studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentidActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        count();
       
    }//GEN-LAST:event_AddActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
         Issue_id.setText("");
              
              Book_name.setText("");
              Student_name.setText("");
              Issue_date.setText("");
              due_date.setText("");
              Penalty1.setText( "");
              Penalty.setText("");

        if(!issue_id())
        {
            Penalty1.setText( "Record Not Found");
        }
    }//GEN-LAST:event_Add1ActionPerformed
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new return_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle Add;
    private rojerusan.RSMaterialButtonCircle Add1;
    private javax.swing.JLabel Book_name;
    private javax.swing.JLabel Issue_date;
    private javax.swing.JLabel Issue_id;
    private javax.swing.JLabel Penalty;
    private javax.swing.JLabel Penalty1;
    private javax.swing.JLabel Student_name;
    private javax.swing.JLabel due;
    private javax.swing.JLabel due_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private app.bolivia.swing.JCTextField txt_Bookid;
    private app.bolivia.swing.JCTextField txt_studentid;
    // End of variables declaration//GEN-END:variables
}
